export const CardDetails = [
  {
    id: 1,
    cardTitle: 'Model Answer',
    taskType1: '1',
    taskType2: 'Development',
    taskType3: 'Backlog',
    type: 'Backlog Task',
  },
  {
    id: 2,
    cardTitle: 'Create Calender',
    taskType1: '2',
    taskType2: 'Development',
    taskType3: 'Backlog',
    type: 'To Do Task',
  },
  {
    id: 3,
    cardTitle: 'Product Design',
    taskType1: '3',
    taskType2: 'Project',
    taskType3: 'Backlog',
    type: 'In Process',
  },
  {
    id: 4,
    cardTitle: 'Product Design',
    taskType1: '4',
    taskType2: 'Project',
    taskType3: 'Backlog',
    type: 'Done',
  },
  {
    id: 5,
    cardTitle: 'Product Design',
    taskType1: '5',
    taskType2: 'Project',
    taskType3: 'Backlog',
    type: 'Done',
  },
  {
    id: 6,
    cardTitle: 'Product Design',
    taskType1: '6',
    taskType2: 'Project',
    taskType3: 'Backlog',
    type: 'To Do Task',
  },
];
